manager/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :payment_requests, only: [:index] do
    post :accept
    post :reject
  end  
  # Defines the root path route ("/")
  # root "articles#index"
end

manager/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

manager/app/models/payment_request.rb
class PaymentRequest < ApplicationRecord
  validates :amount, numericality: { greater_than: 0, only_integer: true  }
  validates :currency, inclusion: { in: %w(USD EUR)}
  validates :description, presence: true

  state_machine :status, initial: :pending do
    event :accept do
      transition %i[pending] => :accepted
    end

    event :reject do
      transition %i[pending] => :rejected
    end
  end
end

manager/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

manager/app/controllers/payment_requests_controller.rb
class PaymentRequestsController < ApplicationController
  before_action :set_payment_request, only: %i[ accept reject ]

  # GET /payment_requests 
  def index
    @payment_requests = PaymentRequest.all
  end

  def accept
    if @payment_request.accept
      Publisher.publish('payment_requests', PaymentRequestSerializer.new(@payment_request).serializable_hash)
    end  
    redirect_to payment_requests_url
  end

  def reject
    if @payment_request.reject
      Publisher.publish('payment_requests', PaymentRequestSerializer.new(@payment_request).serializable_hash)
    end  
    redirect_to payment_requests_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_request
      @payment_request = PaymentRequest.find(params[:payment_request_id])
    end
  end

manager/app/helpers/application_helper.rb
module ApplicationHelper
end

manager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">  
      <div class="row">  
        <%= yield %>
      </div>
    </div>
  </body>
</html>

manager/app/views/payment_requests/_payment_request.html.erb
<div id="<%= dom_id payment_request %>">
  <p>
    <strong>Amount:</strong>
    <%= payment_request.amount %>
  </p>

  <p>
    <strong>Currency:</strong>
    <%= payment_request.currency %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= payment_request.description %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= payment_request.status %>
  </p>

  <% if payment_request.pending? %>	
    <div class="container">
      <div class="row">
        <div class="col-sm">
          <%= button_to "Accept", payment_request_accept_path(payment_request), method: :post, class: "btn btn-outline-primary btn-lg" %>
        </div>
        <div class="col-sm">
          <%= button_to "Reject", payment_request_reject_path(payment_request), method: :post, class: "btn btn-outline-danger btn-lg"%>
        </div>
      </div>
    </div>
  <% end %>	
</div>

manager/app/views/payment_requests/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="cal-lg-8 mx-auto">
  <h1>Payment requests</h1>
  <div id="pyment-requests">
    <% @payment_requests.each do |payment_request| %>
      <div class="card shadow mb-3">
        <div class="card-body">
          <%= render payment_request %>
        </div>
      </div> 
    <% end %>
  </div>
</div>