contractor/config/routes.rb
Rails.application.routes.draw do
  resources :payment_requests, only: [:new, :create, :index, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

contractor/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

contractor/app/models/payment_request.rb
class PaymentRequest < ApplicationRecord
  validates :amount, numericality: { greater_than: 0, only_integer: true  }
  validates :currency, inclusion: { in: %w(USD EUR)}
  validates :description, presence: true

  state_machine :status, initial: :pending do
    event :accept do
      transition %i[pending] => :accepted
    end

    event :reject do
      transition %i[pending] => :rejected
    end
  end
end

contractor/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

contractor/app/controllers/payment_requests_controller.rb
class PaymentRequestsController < ApplicationController
  before_action :set_payment_request, only: %i[ destroy ]

  # GET /payment_requests 
  def index
    @payment_requests = PaymentRequest.all
  end

  # GET /payment_requests/new
  def new
    @payment_request = PaymentRequest.new
  end

  # POST /payment_requests 
  def create
    @payment_request = PaymentRequest.new(payment_request_params)

    respond_to do |format|
      if @payment_request.save
        Publisher.publish("payment_requests", PaymentRequestSerializer.new(@payment_request).serializable_hash)
        format.html { redirect_to payment_requests_url, notice: "Payment request was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_requests/1 
  def destroy
    @payment_request.destroy

    respond_to do |format|
      format.html { redirect_to payment_requests_url, notice: "Payment request was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_request
      @payment_request = PaymentRequest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_request_params
      params.require(:payment_request).permit(:amount, :currency, :description)
    end
end

contractor/app/helpers/application_helper.rb
module ApplicationHelper
end

contractor/app/helpers/payment_requests_helper.rb
module PaymentRequestsHelper
end

contractor/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contractor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">  
      <div class="row">  
        <%= yield %>
      </div>
    </div>
  </body>
</html>

contractor/app/views/payment_requests/_form.html.erb
<%= form_with(model: payment_request) do |form| %>
  <% if payment_request.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment_request.errors.count, "error") %> prohibited this payment_request from being saved:</h2>

      <ul>
        <% payment_request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :currency, style: "display: block" %>
    <%= form.select :currency, ['USD', 'EUR'], {}, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group mb-3">
    <%= form.submit class: "btn btn-primary btn-lg" %>
    <%= link_to "Back to payment requests", payment_requests_path, class: "btn btn-outline-primary btn-lg" %>
  </div>
<% end %>

contractor/app/views/payment_requests/_payment_request.html.erb
<div id="<%= dom_id payment_request %>">
  <p>
    <strong>Amount:</strong>
    <%= payment_request.amount %>
  </p>

  <p>
    <strong>Currency:</strong>
    <%= payment_request.currency %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= payment_request.description %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= payment_request.status %>
  </p>

  <%= button_to "Destroy this payment request", payment_request, method: :delete %>
</div>

contractor/app/views/payment_requests/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="cal-lg-8 mx-auto">
  <h1>Payment requests</h1>
  <div id="pyment-requests">
    <% @payment_requests.each do |payment_request| %>
      <div class="card shadow mb-3">
        <div class="card-body">
          <%= render payment_request %>
        </div>
      </div> 
    <% end %>
  </div>
</div>

<%= link_to "New payment request", new_payment_request_path %>

contractor/app/views/payment_requests/new.html.erb
<div class="col-lg-8 mx-auto">
  <div class="card shadow">
    <div class="card-header">
      <h1 class="card-title">New payment request</h1>
    </div>
    <div class="card-body">
      <%= render "form", payment_request: @payment_request %>
    </div>
  </div>
</div>